### ISSUE TITLE
项目clone后运行client.py报错

### ISSUE THREAD

**Issue by Zzz233** [chenjiandongx/async-proxy-pool#12]
Traceback (most recent call last):
  File "D:/Program Files/PycharmProjects/untitled/async-proxy-pool/client.py", line 8, in <module>
    run_schedule()
  File "D:\Program Files\PycharmProjects\untitled\async-proxy-pool\async_proxy_pool\scheduler.py", line 20, in run_schedule
    schedule.every(CRAWLER_RUN_CYCLE).minutes.do(crawler.run).run()
  File "D:\Program Files\PycharmProjects\untitled\venv\lib\site-packages\schedule\__init__.py", line 466, in run
    ret = self.job_func()
  File "D:\Program Files\PycharmProjects\untitled\async-proxy-pool\async_proxy_pool\crawler.py", line 34, in run
    redis_conn.add_proxy(proxy)
  File "D:\Program Files\PycharmProjects\untitled\async-proxy-pool\async_proxy_pool\database.py", line 45, in add_proxy
    self.redis.zadd(REDIS_KEY, proxy, score)
  File "D:\Program Files\PycharmProjects\untitled\venv\lib\site-packages\redis\client.py", line 2320, in zadd
    for pair in iteritems(mapping):
  File "D:\Program Files\PycharmProjects\untitled\venv\lib\site-packages\redis\_compat.py", line 109, in iteritems
    return iter(x.items())
AttributeError: 'str' object has no attribute 'items'

**Comment by Zzz233** [comment]
重新搭建环境后正常运行!
应该是我自己的环境原因
