### ISSUE TITLE
redis zadd 参数问题

### ISSUE THREAD

**Issue by venyowong** [chenjiandongx/async-proxy-pool#2]
$ python3 client.py
2018-11-21 09:57:07,169 - Crawler working...
Traceback (most recent call last):
  File "client.py", line 7, in <module>
    run_schedule()
  File "/mnt/d/repos/async-proxy-pool/async_proxy_pool/scheduler.py", line 20, in run_schedule
    schedule.every(CRAWLER_RUN_CYCLE).minutes.do(crawler.run).run()
  File "/home/venyo/.local/lib/python3.5/site-packages/schedule/__init__.py", line 411, in run
    ret = self.job_func()
  File "/mnt/d/repos/async-proxy-pool/async_proxy_pool/crawler.py", line 35, in run
    redis_conn.add_proxy(proxy)
  File "/mnt/d/repos/async-proxy-pool/async_proxy_pool/database.py", line 47, in add_proxy
    self.redis.zadd(REDIS_KEY, proxy, score)
  File "/home/venyo/.local/lib/python3.5/site-packages/redis/client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "/home/venyo/.local/lib/python3.5/site-packages/redis/_compat.py", line 123, in iteritems
    return iter(x.items())
AttributeError: 'str' object has no attribute 'items'

**Comment by venyowong** [comment]
这个问题是因为我使用 `pip install -r requirements.txt` 命令安装依赖库的时候，默认安装的是 redis 3.0.1，新版本的方法签名有修改，所以 database.py 里面的代码就会报错。
建议在依赖库后面指明详细的版本号

**Comment by chenjiandongx** [comment]
ok 改好了
