### ISSUE TITLE
报错了,py3.7.1+centos

### ISSUE THREAD

**Issue by amhoho** [chenjiandongx/async-proxy-pool#5]
```
[2018-11-27 21:53:37 +0800] [5347] [INFO] Goin' Fast @ http://localhost:3289
[2018-11-27 21:53:37 +0800] [5347] [ERROR] Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1106, in uvloop.loop.Loop._create_server
  File "uvloop/handles/tcp.pyx", line 88, in uvloop.loop.TCPServer.bind
  File "uvloop/handles/streamserver.pyx", line 89, in uvloop.loop.UVStreamServer                                                                                                                                                             ._fatal_error
  File "uvloop/handles/tcp.pyx", line 86, in uvloop.loop.TCPServer.bind
  File "uvloop/handles/tcp.pyx", line 26, in uvloop.loop.__tcp_bind
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sanic/server.py", line 612, in se                                                                                                                                                             rve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1446, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1667, in create_server
  File "uvloop/loop.pyx", line 1111, in uvloop.loop.Loop._create_server
OSError: [Errno 99] error while attempting to bind on address ('::1', 3289, 0, 0                                                                                                                                                             ): cannot assign requested address
[2018-11-27 21:53:37 +0800] [5347] [INFO] Server Stopped
[root@yj007 async-proxy-pool]# python3 server.py
[2018-11-27 21:53:47 +0800] [5355] [INFO] Goin' Fast @ http://localhost:3289
[2018-11-27 21:53:47 +0800] [5355] [ERROR] Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1106, in uvloop.loop.Loop._create_server
  File "uvloop/handles/tcp.pyx", line 88, in uvloop.loop.TCPServer.bind
  File "uvloop/handles/streamserver.pyx", line 89, in uvloop.loop.UVStreamServer                                                                                                                                                             ._fatal_error
  File "uvloop/handles/tcp.pyx", line 86, in uvloop.loop.TCPServer.bind
  File "uvloop/handles/tcp.pyx", line 26, in uvloop.loop.__tcp_bind
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sanic/server.py", line 612, in se                                                                                                                                                             rve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1446, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1667, in create_server
  File "uvloop/loop.pyx", line 1111, in uvloop.loop.Loop._create_server
OSError: [Errno 99] error while attempting to bind on address ('::1', 3289, 0, 0                                                                                                                                                             ): cannot assign requested address
[2018-11-27 21:53:47 +0800] [5355] [INFO] Server Stopped
```

**Comment by chenjiandongx** [comment]
奇怪 要不你 sanic 启动换个端口试试

**Comment by amhoho** [comment]
照旧:
```
[2018-11-29 00:29:46 +0800] [5077] [INFO] Goin' Fast @ http://localhost:55556
[2018-11-29 00:29:46 +0800] [5077] [ERROR] Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1106, in uvloop.loop.Loop._create_server
  File "uvloop/handles/tcp.pyx", line 88, in uvloop.loop.TCPServer.bind
  File "uvloop/handles/streamserver.pyx", line 89, in uvloop.loop.UVStreamServer._fatal_error
  File "uvloop/handles/tcp.pyx", line 86, in uvloop.loop.TCPServer.bind
  File "uvloop/handles/tcp.pyx", line 26, in uvloop.loop.__tcp_bind
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 612, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1446, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1667, in create_server
  File "uvloop/loop.pyx", line 1111, in uvloop.loop.Loop._create_server
OSError: [Errno 99] error while attempting to bind on address ('::1', 55556, 0, 0): cannot assign requested address
[2018-11-29 00:29:46 +0800] [5077] [INFO] Server Stopped
[root@yj007 ~]#

```

**Comment by amhoho** [comment]
改成127.0.0.1 可以了

**Comment by chenjiandongx** [comment]
OK
